---
- name: Get pyenv
  git:
    repo: 'https://github.com/pyenv/pyenv.git'
    dest: '{{ python_pyenv_directory }}'

- name: Get pyenv-virtualenv
  git:
    repo: 'https://github.com/pyenv/pyenv-virtualenv.git'
    dest: '{{ python_pyenv_directory }}/plugins/pyenv-virtualenv'

- name: Run in pyenv environment
  environment:
    PYENV_ROOT: "{{ python_pyenv_directory }}"
  block:
    - name: Install Python versions
      command: '{{ python_pyenv_executable }} install {{ item }}'
      register: result
      failed_when: >
        result.rc != 0 and not result.stderr.endswith('already exists')
      changed_when: result.rc == 0
      with_items:
        - 2.7.16
        - 3.7.4

    - name: Check global Python version 
      command: '{{ python_pyenv_executable }} global'
      register: python_pyenv_global_version_check
      changed_when: false

    - name: Set global Python version
      command: >
        {{ python_pyenv_executable }} global {{ python_pyenv_global_version }}
      when: python_pyenv_global_version_check.stdout != python_pyenv_global_version

    - name: Make pipx virtual environment
      command: >
        {{ python_pyenv_executable }} virtualenv
        {{ python_pyenv_global_version }} pipx
      register: result
      failed_when: >
        result.rc != 0 and not result.stderr.endswith('already exists.')
      changed_when: result.rc == 0

    - name: Run in pipx pyenv environment
      environment:
        PYENV_VERSION: pipx
      block:
      - name: Install pipx
        command: '{{ python_pyenv_executable }} exec pip install --upgrade pipx'
        register: result
        changed_when: >
          result.rc == 0 and not 'Requirement already up-to-date: pipx' in result.stdout

      - name: Install Python executables
        command: "{{ python_pyenv_executable }} exec pipx install {{ item }}"
        register: result
        changed_when: >
          result.rc == 0 and not 'already seems to be installed' in result.stdout
        with_items:
          - ansible
          - black
          - csvkit
          - docker-compose
          - isort
          - legit
          - pipenv
          - poetry
          - pre-commit
          - visidata
          - yamllint
