---

- name: Check if Stack is installed
  stat:
    path: "{{ stack_bin_path }}"
  register: stack_stat_result

- name: Download and install Stack
  when: >
    not (stack_stat_result.stat.executable is defined
      and stack_stat_result.stat.executable)
  block:
    - name: Create temporary download file
      tempfile:
        state: file
        suffix: ".tar.gz"
      register: stack_archive
      changed_when: false

    - name: Download Stack
      get_url:
        url: "{{ stack_download_url }}"
        dest: "{{ stack_archive.path }}"
        checksum: "sha1:379006b3c09950bb8574fb70b653aa4c9a0ebfc7"
      changed_when: false

    - name: Create stack directories
      file:
        path: "{{ item }}"
        state: directory
        mode: u=rwx,g=rx,o=rx
      with_items:
        - "{{ stack_root_dir }}"
        - "{{ stack_bin_dir }}"

    - name: Extract Stack
      unarchive:
        src: "{{ stack_archive.path }}"
        dest: "{{ stack_bin_dir }}"
        extra_opts:
          - "{{ stack_archive_bin_path }}"
          - "--strip-components=1"

    - name: Remove download
      file:
        path: "{{ stack_archive.path }}"
        state: absent
      changed_when: false

- name: Run in Stack environment
  environment:
    STACK_ROOT: "{{ stack_root_dir }}"
    LC_ALL: "en_US.UTF-8"
  block:
    - name: Upgrade Stack
      command: "{{ stack_bin_path }} upgrade"
      register: stack_upgrade_result
      changed_when: >
        not (stack_upgrade_result.stderr_lines is defined
          and "Skipping binary upgrade, you are already running the most recent version"
            in stack_upgrade_result.stderr_lines)

    - name: Set Stack installation prefix
      copy:
        content: "{{ stack_config | to_nice_yaml }}"
        dest: "{{ stack_config_file }}"

    - name: Check if hledger is installed
      stat:
        path: "{{ stack_bin_dir }}/hledger"
      register: hledger_stat_result

    - name: Install hledger
      when: >
        not (hledger_stat_result.stat.executable is defined
            and hledger_stat_result.stat.executable)
      command: >
        {{ stack_bin_path }} install --resolver=lts-14.3
        hledger-lib-1.15.2
        hledger-1.15.2
        hledger-web-1.15
        hledger-ui-1.15

    - name: Install ShellCheck
      command: "{{ stack_bin_path }} install ShellCheck"
      args:
        creates: "{{ stack_bin_dir }}/shellcheck"
