---

- name: Add Pick repository key
  register: result
  retries: 10
  until: not result.failed
  apt_key:
    id: 0EDF8453E8783FF786AF6DED2D2F9F912F2229FF
    keyserver: keyserver.ubuntu.com
    state: present

- name: Add Pick repository
  register: result
  retries: 10
  until: not result.failed
  apt_repository:
    repo: deb http://ppa.launchpad.net/sil/pick/ubuntu xenial main
    filename: pick

- name: Add filename to managed config files list
  set_fact:
    base_apt_config_files: >
      {{ base_apt_config_files + ['pick'] }}

- name: Install Pick
  register: result
  retries: 10
  until: not result.failed
  apt:
    update_cache: true
    state: latest
    name: pick-colour-picker
