- name: Ubuntu repositories enabled
  apt_repository:
    repo: '{{ item }}'
    state: present
  with_items:
    - 'deb http://th.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main restricted'
    - 'deb http://th.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates main restricted'
    - 'deb http://th.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe'
    - 'deb http://th.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe'
    - 'deb http://th.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} multiverse'
    - 'deb http://th.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates multiverse'
    - 'deb http://th.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-backports main restricted universe multiverse'
    - 'deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security main restricted'
    - 'deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security universe'
    - 'deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security multiverse'
    - 'deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner'

- name: Google Chrome APT key added
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    id: 9534C9C4130B4DC9927992BF4F30B6B4C07CB649
    state: present

- name: Google Chrome repo enabled
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
    state: present

- name: Skype APT key added
  apt_key:
    url: https://repo.skype.com/data/SKYPE-GPG-KEY
    id: F60A017E3CA5558FAF2439556B4A0000A4EBB320
    state: present

- name: Skype repo enabled
  apt_repository:
    repo: deb [arch=amd64] https://repo.skype.com/deb stable main
    filename: skype-stable
    state: present

- name: Signal APT key added
  apt_key:
    url:  https://updates.signal.org/desktop/apt/keys.asc
    id: D980A17457F6FB06
    state: present

- name: Signal repo enabled
  apt_repository:
    repo: deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
    filename: signal
    state: present

- name: Pick APT key added
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0EDF8453E8783FF786AF6DED2D2F9F912F2229FF

- name: Pick repo enabled
  apt_repository:
    repo: deb http://ppa.launchpad.net/sil/pick/ubuntu xenial main
    filename: pick

- name: Update APT cache
  apt:
    update_cache: yes

- name: Unused packages removed
  apt:
    name: '{{ item }}'
    state: absent
  with_items:
    - gedit
    - nano

- name: Packages added
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    # Applications
    - anki
    - audacity
    - calibre
    - google-chrome-stable
    - hexchat
    - mplayer
    - mpv
    - pinta
    - quodlibet
    - remmina
    - signal-desktop
    - simplescreenrecorder
    - skypeforlinux
    - usb-creator-gtk
    - vim-gtk3
    - virtualbox
    - virtualbox-ext-pack
    - virtualbox-qt

    # Handy GUI tools
    - pick-colour-picker
    - xclip

    # Games
    - wesnoth

    # Appearance
    - fonts-hack
    - fonts-noto
    - gnome-tweak-tool

    # My languages
    - firefox-locale-en
    - firefox-locale-sv
    - firefox-locale-th
    - language-pack-gnome-en
    - language-pack-gnome-sv
    - language-pack-gnome-th
    - wamerican
    - wbritish
    - wswedish

    # Handy terminal tools
    - curl
    - jq
    - mmv
    - mosh
    - pandoc
    - rar
    - unrar
    - unzip
    - tmux
    - xmlstarlet
    - zip

    # Development tools
    - bzr
    - docker.io
    - git
    - libperl-critic-perl
    - python-minimal
    - python-pip
    - python3-minimal
    - python3-pip
    - shellcheck
    - sqlite3
    - subversion
    - vagrant

    # Network tools
    - net-tools
    - traceroute
    - network-manager-openconnect-gnome
    - network-manager-openvpn-gnome
    - network-manager-vpnc-gnome

    # Printing
    - python3-smbc
    - smbclient

    # System tools
    - duply
    - krb5-user
    - ubuntu-restricted-addons

    # Necessary to install Ansible with pip
    - libssl-dev

    # Useful for scripts that need secrets
    - libsecret-tools


- name: Firefox set as default browser
  alternatives:
    name: x-www-browser
    path: /usr/bin/firefox

- name: Global keyboard defaults set
  lineinfile:
    path: /etc/default/keyboard
    regexp: '^{{ item.key }}='
    line: '{{ item.key }}="{{ item.value }}"'
  with_items:
    - { key: 'XKBLAYOUT', value: 'us' }
    - { key: 'XKBVARIANT', value: 'altgr-intl' }
    - { key: 'XKBOPTIONS', value: 'compose:caps' }
    - { key: 'BACKSPACE', value: 'guess'}
