- name: Ubuntu repositories enabled
  apt_repository:
    repo: '{{ item }}'
    state: present
  with_items:
    - 'deb http://th.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main restricted'
    - 'deb http://th.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates main restricted'
    - 'deb http://th.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe'
    - 'deb http://th.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe'
    - 'deb http://th.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} multiverse'
    - 'deb http://th.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates multiverse'
    - 'deb http://th.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-backports main restricted universe multiverse'
    - 'deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security main restricted'
    - 'deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security universe'
    - 'deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security multiverse'
    - 'deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner'

- name: Google Chrome APT key added
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    id: 9534C9C4130B4DC9927992BF4F30B6B4C07CB649
    state: present

- name: Google Chrome repo enabled
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
    state: present

- name: Skype APT key added
  apt_key:
    url: https://repo.skype.com/data/SKYPE-GPG-KEY
    id: F60A017E3CA5558FAF2439556B4A0000A4EBB320
    state: present

- name: Skype repo enabled
  apt_repository:
    repo: deb [arch=amd64] https://repo.skype.com/deb stable main
    filename: skype-stable
    state: present

- name: Signal APT key added
  apt_key:
    url:  https://updates.signal.org/desktop/apt/keys.asc
    id: D980A17457F6FB06
    state: present

- name: Signal repo enabled
  apt_repository:
    repo: deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
    filename: signal
    state: present

- name: Pick APT key added
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0EDF8453E8783FF786AF6DED2D2F9F912F2229FF

- name: Pick repo enabled
  apt_repository:
    repo: deb http://ppa.launchpad.net/sil/pick/ubuntu xenial main
    filename: pick

- name: Teamviewer APT key added
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: C5E224500C1289C0

- name: Teamviewer repo enabled
  apt_repository:
    repo: '{{ item }}'
    filename: teamviewer
  with_items:
    - deb http://linux.teamviewer.com/deb stable main
    - deb http://linux.teamviewer.com/deb preview main

- name: docker-gc repo enabled
  apt_repository:
    repo: ppa:nschloe/docker-gc-nightly
    filename: docker-gc

- name: Picard repo enabled
  apt_repository:
    repo: ppa:musicbrainz-developers/stable
    filename: musicbrainz

- name: MellowPlayer APT key added
  apt_key:
    id: E481C081DB2A84F7
    url: https://download.opensuse.org/repositories/home:ColinDuquesnoy/xUbuntu_18.04/Release.key

- name: MellowPlayer repo enabled
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/home:/ColinDuquesnoy/xUbuntu_18.04/ /
    filename: mellowplayer

- name: SWI Prolog APT key added
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EF8406856DBFCA18

- name: SWI Prolog repo enabled
  apt_repository:
    repo: deb http://ppa.launchpad.net/swi-prolog/devel/ubuntu bionic main
    filename: swi-prolog

- name: Update APT cache
  apt:
    update_cache: yes
  changed_when: false

- name: Packages added
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    # Applications
    - anki
    - audacity
    - calibre
    - evolution
    - evolution-ews
    - google-chrome-stable
    - hexchat
    - mellowplayer
    - mplayer
    - mpv
    - picard
    - quodlibet
    - remmina
    - signal-desktop
    - simplescreenrecorder
    - skypeforlinux
    - teamviewer
    - usb-creator-gtk
    - vim-gtk3
    - virtualbox
    - virtualbox-ext-pack
    - virtualbox-qt

    # Handy GUI tools
    - gnome-clocks
    - pick-colour-picker
    - xclip

    # Games
    - wesnoth

    # Appearance
    - fonts-noto
    - gnome-tweak-tool

    # My languages
    - firefox-locale-en
    - firefox-locale-sv
    - firefox-locale-th
    - language-pack-gnome-en
    - language-pack-gnome-sv
    - language-pack-gnome-th
    - wamerican
    - wbritish
    - wswedish

    # Handy terminal tools
    - curl
    - httpie
    - jq
    - libimage-exiftool-perl
    - mmv
    - moreutils
    - mosh
    - pandoc
    - rar
    - unrar
    - unzip
    - tmux
    - woof
    - xmlstarlet
    - zip
    - zsync

    # Development tools
    - bats
    - build-essential
    - bzr
    - debhelper
    - devscripts
    - dh-make
    - docker-compose
    - docker-gc
    - docker.io
    - git
    - graphviz
    - libperl-critic-perl
    - nodejs
    - npm
    - python-minimal
    - python-pip
    - python3-minimal
    - python3-pip
    - shellcheck
    - swi-prolog
    - sqlite3
    - subversion
    - tidy
    - vagrant

    # Network tools
    - autossh
    - dnsmasq
    - net-tools
    - network-manager-openconnect-gnome
    - network-manager-openvpn-gnome
    - network-manager-vpnc-gnome
    - resolvconf
    - traceroute
    - whois

    # Printing
    - python3-smbc
    - smbclient

    # System tools
    - chrony
    - duply
    - krb5-user
    - ubuntu-restricted-addons

    # Ansible dependency
    - libssl-dev

    # Erlang dependencies
    - autoconf
    - libncurses5-dev

    # Useful for scripts that need secrets
    - libsecret-tools


- name: Firefox set as default browser
  alternatives:
    name: x-www-browser
    path: /usr/bin/firefox

- name: Global keyboard defaults set
  lineinfile:
    path: /etc/default/keyboard
    regexp: '^{{ item.key }}='
    line: '{{ item.key }}="{{ item.value }}"'
  with_items:
    - { key: 'XKBLAYOUT', value: 'us' }
    - { key: 'XKBVARIANT', value: 'altgr-intl' }
    - { key: 'XKBOPTIONS', value: 'compose:caps' }
    - { key: 'BACKSPACE', value: 'guess'}

- name: Change GNOME Shell font
  patch:
    src: gnome_shell_font.diff
    basedir: /usr/share/gnome-shell/theme

- name: Teamviewer service disabled on startup
  copy:
    src: rc.local
    dest: /etc/rc.local
    mode: u+rwx,g+rx,o+rx

- name: systemd-resolved stub listener disabled
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^DNSStubListener='
    line: 'DNSStubListener=no'

- name: systemd-resolved restarted
  service:
    name: systemd-resolved
    state: restarted

- name: dnsmasq configured
  copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    mode: u+rw,g+r,o+r

- name: dnsmasq restarted
  service:
    name: dnsmasq
    state: restarted

- name: resolvconf configured
  copy:
    src: resolv.conf.base
    dest: /etc/resolvconf/resolv.conf.d/base
    mode: u+rw,g+r,o+r

- name: resolvconf restarted
  service:
    name: resolvconf
    state: restarted
