---

- name: Add VirtualBox repository key
  register: result
  retries: 10
  until: not result.failed
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    id: A2F683C52980AECF
    state: present

- name: Add VirtualBox repository
  register: result
  retries: 10
  until: not result.failed
  apt_repository:
    repo: >-
      deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian
      {{ ansible_distribution_release }}
      contrib
    filename: docker

- name: Add filenames to managed config files list
  set_fact:
    base_apt_config_files: >
      {{ base_apt_config_files + ['virtualbox'] }}

- name: Install VirtualBox
  register: result
  retries: 10
  until: not result.failed
  apt:
    update_cache: true
    state: latest
    name: virtualbox-6.1

- name: Users added to VirtualBox group
  user:
    name: "{{ item }}"
    groups: vboxusers
    append: true
  with_items: "{{ users }}"

- name: Load kernel module
  modprobe:
    name: vboxdrv
    state: present
  register: kernel_module_check
  ignore_errors: true

- when: not kernel_module_check.failed
  block:
    - name: Get VirtualBox version
      command: vboxmanage --version
      changed_when: false
      register: vboxmanage_version_result

    - name: Store VirtualBox version
      set_fact:
        virtualbox_version: >-
          {{ vboxmanage_version_result.stdout | regex_replace('r.*$') }}

    - name: Get list of installed extension packs
      shell: >-
        vboxmanage list extpacks
      changed_when: false
      register: vboxmanage_list_expacks_result

    - when: >-
          not vboxmanage_list_expacks_result.stdout_lines
          | map('regex_search',
                '^Version:\s*' ~ (virtualbox_version | regex_escape()) ~ '$')
          | select("string")
          | list
          | length
          | bool
      block:
        - name: Download VirtualBox extension Pack
          get_url:
            url: "http://download.virtualbox.org/virtualbox/\
                  {{ virtualbox_version }}\
                  /Oracle_VM_VirtualBox_Extension_Pack-\
                  {{ virtualbox_version}}\
                  .vbox-extpack"
            dest: "/tmp/Oracle_VM_VirtualBox_Extension_Pack-\
                   {{ virtualbox_version }}\
                   .vbox-extpack"

        - name: Install VirtualBox extension Pack
          command: "vboxmanage extpack install --replace \
                    /tmp/Oracle_VM_VirtualBox_Extension_Pack-\
                    {{ virtualbox_version}}\
                    .vbox-extpack"
          args:
            stdin: y
