- name: Check if Quicklisp is installed
  stat:
    path: '{{ quicklisp_directory }}'
  register: quicklisp_directory_stat

- name: Install Quicklisp
  when: not quicklisp_directory_stat.stat.exists
  block:
    - name: Get Quicklisp installation script
      get_url:
        url: https://beta.quicklisp.org/quicklisp.lisp
        checksum: sha256:4a7a5c2aebe0716417047854267397e24a44d0cce096127411e9ce9ccfeb2c17
        dest: '{{ quicklisp_installer_filename }}'

    - name: Run Quicklisp installation
      command: >
        sbcl
        --no-sysinit
        --no-userinit
        --load {{ quicklisp_installer_filename }}
        --eval
        '(quicklisp-quickstart:install :path "{{ quicklisp_directory }}")'
        --quit

- name: Update Quicklisp client
  command: "sbcl --eval '(ql:update-client :prompt nil)' --quit"
  register: result
  changed_when: >
    'The most up-to-date client' not in result.stdout

- name: Update Quicklisp software
  command: >
    sbcl --eval '(ql:update-dist "quicklisp" :prompt nil)' --quit
  register: result
  changed_when: >
    'You already have the latest version of "quicklisp"' not in result.stdout
