---
image: alpine/latest
oauth: >-
  git.sr.ht/PROFILE:RO
  git.sr.ht/REPOSITORIES:RW
  builds.sr.ht/PROFILE:RO
  builds.sr.ht/JOBS:RW
  builds.sr.ht/SECRETS:RO
packages:
  - emacs-nox
  - hut
sources:
  - https://git.sr.ht/~bkhl/dotfiles
  - https://git.sr.ht/~bkhl/elektrubadur.se
tasks:
  - generate-html: >-
      make -C dotfiles README.html
  - complete-unless-main: >-
      git -C dotfiles diff --quiet --exit-code origin/main || complete-build
  - publish-readme: |
      cd dotfiles
      hut git update --readme README.html
  - trigger-web-page-build: >-
      hut builds submit elektrubadur.se/.build.yml
triggers:
  - action: email
    condition: failure
    to: "Björn Lindström <bkhl@elektrubadur.se>"
