- name: Check for CLI client
  stat:
    path: "{{ exercism_bin_path }}"
  register: exercism_check

- when: >
    exercism_check.stat.executable is not defined
    or not exercism_check.stat.executable
  block:
    - name: Download client
      get_url:
        url: https://github.com/exercism/cli/releases/download/v3.0.5/exercism-linux-64bit.tgz
        dest: /tmp/exercism-linux-64bit.tgz
        checksum: sha256:d32a63542ca3588faeaa02f6f2a28c50a6eec50354d2838cd82470d262dff020

    - name: Check for bin directory
      file:
        path: "{{ user_bin_directory }}"
        state: directory
        mode: u=rwx,g=rx,o=rx

    - name: Unpack client
      unarchive:
        src: /tmp/exercism-linux-64bit.tgz
        dest: "{{ user_bin_directory }}/"
        exclude: "shell"

    - name: Make client executable
      file:
        path: "{{ exercism_bin_path }}"
        state: file
        mode: u=rwx,g=rx,o=rx

- name: Read configuration
  slurp:
    src: "{{ exercism_config_file }}"
  register: check_exercism_configuration
  ignore_errors: true

- block:
    - name: Create configuration directory
      file:
        path: "{{ exercism_config_dir }}"
        state: directory
        mode: u=rwx,g=rx,o=rx

    - name: Create empty configuration
      set_fact:
        configuration_content: {}

  when: check_exercism_configuration.failed

- block:
    - name: Use existing configuration
      set_fact:
        configuration_content: "{{ check_exercism_configuration.content | b64decode }}"
  when: not check_exercism_configuration.failed

- name: Set workspace
  set_fact:
    updated_exercism_configuration: >-
      {{
      configuration_content
      | default([])
      | combine({
        "workspace": exercism_workspace,
        "apibaseurl": "https://api.exercism.io/v1"
        })
      }}

- name: Write configuration
  copy: 
    content: "{{ updated_exercism_configuration | to_nice_json }}" 
    dest: "{{ exercism_config_file }}"
    mode: u=rw,g=r,o=r
