[buildPlans.iosevka-bkhl-sans-normal]
family = "Iosevka BKHL Sans Normal"
serifs = "sans"
spacing = "normal"
no-ligation = true
no-cv-ss = true

  [buildPlans.iosevka-bkhl-sans-normal.variants.design]
  capital-q = "open-swash"

  f = "serifless-crossbar-at-x-height"
  i = "zshaped"
  l = "zshaped"
  m = "short-leg-serifless"
  t = "bent-hook-asymmetric"
  y = "cursive-serifless"

  cyrl-capital-u = "cursive-serifless"

  long-s = "bent-hook-tailed"
  eszet = "longs-s-lig-tailed-serifless"

  capital-lambda = "curly-serifless"
  lower-lambda = "tailed-turn"

  zero = "reverse-slashed"
  one = "no-base-long-top-serif"
  five = "upright-flat"
  
  ampersand = "upper-open"
  asterisk = "penta-low"
  at = "fourfold-tall"
  cent = "open"
  dollar = "open"
  guillemet = "straight"
  number-sign = "upright-tall"
  pilcrow = "low"
  underscore = "low"

[buildPlans.iosevka-bkhl-sans-fixed]
family = "Iosevka BKHL Sans Fixed"
serifs = "sans"
spacing = "fixed"
no-ligation = true
no-cv-ss = true

  [buildPlans.iosevka-bkhl-sans-fixed.variants]
  inherits = "buildPlans.iosevka-bkhl-sans-normal"

[buildPlans.iosevka-bkhl-serif-normal]
family = "Iosevka BKHL Serif Normal"
serifs = "slab"
spacing = "normal"
no-ligation = true
no-cv-ss = true

  [buildPlans.iosevka-bkhl-serif-normal.variants]
  inherits = "buildPlans.iosevka-bkhl-sans-normal"

    [buildPlans.iosevka-bkhl-serif-normal.variants.design]
    f = "serifed-crossbar-at-x-height"
    g = "double-storey"
    i = "serifed"
    l = "serifed"
    m = "short-leg-serifed"
    t = "bent-hook"
    y = "cursive-serifed"

    cyrl-capital-u = "cursive-serifed"

    long-s = "bent-hook-bottom-serifed"
    eszet = "longs-s-lig-tailed-middle-serifed"

    capital-lambda = "curly-base-serifed"

    one = "base-long-top-serif"
    five = "upright-arched"

    guillemet = "curly"

    [buildPlans.iosevka-bkhl-serif-normal.variants.italic]
    g = "double-storey-open"

[buildPlans.iosevka-bkhl-serif-fixed]
family = "Iosevka BKHL Serif Fixed"
serifs = "slab"
spacing = "fixed"
no-ligation = true
no-cv-ss = true

  [buildPlans.iosevka-bkhl-serif-fixed.variants]
  inherits = "buildPlans.iosevka-bkhl-serif-normal"
