[buildPlans.iosevka-bkhl-default]
family = "Iosevka BKHL Default"
spacing = "normal"
serifs = "slab"
no-ligation = true
no-cv-ss = true

[buildPlans.iosevka-bkhl-default.variants.design]
capital-q = "open-swash"

g = "double-storey"
m = "short-leg-serifed"
y = "cursive-serifed"

long-s = "bent-hook-tailed"
eszet = "longs-s-lig-tailed"

turn-v = "curly"
lower-lambda = "curly-turn"

zero = "reverse-slashed"
one = "base-long-top-serif"
six = "closed-contour"
nine = "closed-contour"

asterisk = "penta-low"
underscore = "low"
number-sign = "upright-tall"
ampersand = "upper-open"
at = "fourfold-solid-inner-tall"
dollar = "open"
pilcrow = "low"

[buildPlans.iosevka-bkhl-default.variants.italic]
g = "double-storey-open"

[buildPlans.iosevka-bkhl-fixed]
family = "Iosevka BKHL Fixed"
spacing = "fixed"
serifs = "slab"
no-ligation = true
no-cv-ss = true

[buildPlans.iosevka-bkhl-fixed.variants]
inherits = "buildPlans.iosevka-bkhl-default"
