[buildPlans.iosevka-bkhl-default]
family = "Iosevka BKHL Default"
spacing = "default"
serifs = "slab"
no-ligation = true
no-cv-ss = true

[buildPlans.iosevka-bkhl-default.variants.design]
g = "double-storey"
m = "short-leg"
y = "cursive"

eszet = "longs-s-lig"

lower-lambda = "curly-turn"

zero = "reverse-slashed"
one = "base-long-top-serif"

dollar = "open"

percent = "rings-continuous-slash"
asterisk = "low"
paragraph-sign = "low"
ampersand = "upper-open"

[buildPlans.iosevka-bkhl-fixed]
family = "Iosevka BKHL Fixed"
spacing = "fixed"
serifs = "slab"
no-ligation = true
no-cv-ss = true

[buildPlans.iosevka-bkhl-fixed.variants.design]
g = "double-storey"
m = "short-leg"
y = "cursive"

eszet = "longs-s-lig"

lower-lambda = "curly-turn"

zero = "reverse-slashed"
one = "base-long-top-serif"

dollar = "open"

percent = "rings-continuous-slash"
asterisk = "low"
paragraph-sign = "low"
ampersand = "upper-open"
