[buildPlans.iosevka-bkhl-default]
family = "Iosevka BKHL Default"
spacing = "normal"
serifs = "slab"
no-ligation = true
no-cv-ss = true

[buildPlans.iosevka-bkhl-default.variants.design]
capital-q = "open-swash"

g = "double-storey"
m = "short-leg"
y = "cursive"

eszet = "longs-s-lig"

lower-lambda = "curly-turn"

zero = "reverse-slashed"
one = "base-long-top-serif"

dollar = "open"

at = "fourfold-solid-inner-tall"
number-sign = "upright-tall"
percent = "rings-continuous-slash"
asterisk = "penta-low"
paragraph-sign = "low"
ampersand = "upper-open"

[buildPlans.iosevka-bkhl-fixed]
family = "Iosevka BKHL Fixed"
spacing = "fixed"
serifs = "slab"
no-ligation = true
no-cv-ss = true

[buildPlans.iosevka-bkhl-fixed.variants.design]
capital-q = "open-swash"

g = "double-storey"
m = "short-leg"
y = "cursive"

eszet = "longs-s-lig"

lower-lambda = "curly-turn"

zero = "reverse-slashed"
one = "base-long-top-serif"

dollar = "open"

at = "fourfold-solid-inner-tall"
number-sign = "upright-tall"
percent = "rings-continuous-slash"
asterisk = "penta-low"
paragraph-sign = "low"
ampersand = "upper-open"
