[buildPlans.iosevka-bkhl-default]
family = "Iosevka BKHL Default"
spacing = "normal"
serifs = "slab"
no-ligation = true
no-cv-ss = true

[buildPlans.iosevka-bkhl-default.variants.design]
capital-q = "open-swash"

g = "double-storey"
m = "short-leg-serifed"
y = "cursive-serifed"

eszet = "longs-s-lig-tailed"

lower-lambda = "curly-turn"

zero = "reverse-slashed"
one = "base-long-top-serif"

asterisk = "penta-low"
number-sign = "upright-tall"
ampersand = "upper-open"
at = "fourfold-solid-inner-tall"
dollar = "open"
pilcrow = "low"

[buildPlans.isoevka-bkhl-default.variants.italic]
g = "double-storey-open"

[buildPlans.iosevka-bkhl-fixed]
family = "Iosevka BKHL Fixed"
spacing = "fixed"
serifs = "slab"
no-ligation = true
no-cv-ss = true

[buildPlans.iosevka-bkhl-fixed.variants]
inherits = "buildPlans.iosevka-bkhl-default"
