- name: Check if SDKMAN is installed
  stat:
    path: "{{ sdkman_init }}"
  register: sdkman_init_check

- name: Install SDKMAN
  when: not sdkman_init_check.stat.exists
  block:
    - name: Get installation script
      get_url:
        url: https://get.sdkman.io/
        dest: /tmp/get-sdkman.sh
        checksum: sha256:42bcab3b32668f77041b10516954be20513e37d81aa65a02d060161dc7874b89

    - name: Install SDKMAN
      command: bash /tmp/get-sdkman.sh

- name: Update SDKMAN
  when: sdkman_init_check.stat.exists is defined and sdkman_init_check.stat.exists
  shell: source {{ sdkman_init }}  && sdk selfupdate
  args:
    executable: /bin/bash

- name: Install SDKMAN packages
  shell: source {{ sdkman_init }}  && sdk install {{ item }}
  args:
    executable: /bin/bash
  with_items: "{{ sdkman_packages }}"
