---
dependencies:
  - role: base
  - role: zeal
  - role: docker
  - role: virtualbox
  - role: pandoc
  - role: teamviewer
  - role: pick
  - role: nextcloud
  - role: skype
  - role: signal
  - role: picard
  - role: vagrant
  - role: racket
