- name: Check setting of click-to-minimize in dock
  command: gsettings get org.gnome.shell.extensions.dash-to-dock click-action
  register: click_to_minimize_check
  ignore_errors: true
  changed_when: false

- name: Enable click-to-minimize in dock
  when: click_to_minimize_check.stdout != "'minimize'"
  command: gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'
