- name: Check if SWI Prolog plugin installed
  command: "{{ asdf_command }} list swiprolog"
  register: swiprolog_check
  ignore_errors: true

- name: SWI Prolog plugin installed
  when: swiprolog_check.rc != 0
  command: "{{ asdf_command }} plugin-add swiprolog"

- name: SWI Prolog plugin up to date
  when: swiprolog_check.rc == 0
  command: "{{ asdf_command }} plugin-update swiprolog"

- name: SWI Prolog 8.0.3 installed
  command: "{{ asdf_command }} install swiprolog 8.0.3"

- name: SWI Prolog 8.0.3 activated
  command: "{{ asdf_command }} global swiprolog 8.0.3"
