autocmd colorscheme * highlight ColorColumn ctermbg=8 guibg='#303030'
set colorcolumn=81
colorscheme torte
syntax on

autocmd FileType make setlocal noexpandtab

set modeline

set autoindent

set shiftwidth=4
set tabstop=4
set expandtab
