---

- name: Add repository key
  register: result
  retries: 10
  until: not result.failed
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    id: D38B4796
    state: present

- name: Add repository
  register: result
  retries: 10
  until: not result.failed
  apt_repository:
    repo: >-
      deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: chrome

- name: Add filenames to managed config files list
  set_fact:
    base_apt_config_files: >
      {{ base_apt_config_files + ['chrome'] }}

- name: Install Chrome
  register: result
  retries: 10
  until: not result.failed
  apt:
    update_cache: true
    state: latest
    name: google-chrome-stable
