---

- name: Add Docker repository key
  register: result
  retries: 10
  until: not result.failed
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 8D81803C0EBFCD88
    state: present

- name: Add Docker repository
  register: result
  retries: 10
  until: not result.failed
  apt_repository:
    repo: >-
      deb [arch=amd64] https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }}
      stable
    filename: docker

- name: Add Docker GC PPA
  register: result
  retries: 10
  until: not result.failed
  apt_repository:
    repo: ppa:nschloe/docker-gc-nightly
    filename: docker-gc

- name: Add filenames to managed config files list
  set_fact:
    base_apt_config_files: >
      {{ base_apt_config_files + ['docker', 'docker-gc'] }}

- name: Install Docker and Docker GC
  register: result
  retries: 10
  until: not result.failed
  apt:
    update_cache: true
    state: latest
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - golang-docker-credential-helpers
      - docker-gc

- name: User added to Docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ admin_users }}"
