---

- name: Add Signal repository key
  register: result
  retries: 10
  until: not result.failed
  apt_key:
    url: https://updates.signal.org/desktop/apt/keys.asc
    id: D980A17457F6FB06
    state: present

- name: Add Signal repository
  register: result
  retries: 10
  until: not result.failed
  apt_repository:
    repo: deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
    filename: signal

- name: Add filenames to managed config files list
  set_fact:
    base_apt_config_files: >
      {{ base_apt_config_files + ['signal'] }}

- name: Install Signal
  register: result
  retries: 10
  until: not result.failed
  apt:
    update_cache: true
    state: latest
    name: signal-desktop
