[buildPlans.iosevka-bkhl-sans-normal]
family = "Iosevka BKHL Sans Normal"
serifs = "sans"
spacing = "normal"
noLigation = true
noCvSs = true

  [buildPlans.iosevka-bkhl-sans-normal.namingOverride]
  description = "Spatial efficient monospace font family for programming. Built from code. http://be5invis.github.io/Iosevka Custom build by Björn Lindström. https://git.sr.ht/~bkhl/dotfiles/tree/main/item/.src/iosevka"

  [buildPlans.iosevka-bkhl-sans-normal.variants.design]
  capital-q = "open-swash"
  capital-w = "rounded-vertical-sides-serifless"

  f = "serifless-crossbar-at-x-height"
  i = "zshaped"
  l = "zshaped"
  m = "short-leg-serifless"
  t = "bent-hook-asymmetric"
  w = "rounded-vertical-sides-serifless"
  y = "cursive-serifless"

  cyrl-capital-u = "cursive-serifless"

  long-s = "bent-hook-tailed"
  capital-eszet = "corner-serifless"
  eszet = "longs-s-lig-tailed-serifless"

  capital-lambda = "curly-serifless"
  lower-lambda = "tailed-turn"

  zero = "reverse-slashed"
  one = "no-base-long-top-serif"
  
  ampersand = "upper-open"
  asterisk = "penta-low"
  at = "fourfold-tall"
  cent = "open"
  dollar = "open"
  guillemet = "straight"
  number-sign = "upright-tall"
  pilcrow = "low"
  underscore = "low"

[buildPlans.iosevka-bkhl-sans-fixed]
family = "Iosevka BKHL Sans Fixed"
serifs = "sans"
spacing = "fixed"
noLigation = true
noCvSs = true

  [buildPlans.iosevka-bkhl-sans-fixed.namingOverride]
  description = "Spatial efficient monospace font family for programming. Built from code. http://be5invis.github.io/Iosevka Custom build by Björn Lindström. https://git.sr.ht/~bkhl/dotfiles/tree/main/item/.src/iosevka"

  [buildPlans.iosevka-bkhl-sans-fixed.variants]
  inherits = "buildPlans.iosevka-bkhl-sans-normal"

[buildPlans.iosevka-bkhl-serif-normal]
family = "Iosevka BKHL Serif Normal"
serifs = "slab"
spacing = "normal"
noLigation = true
noCvSs = true

  [buildPlans.iosevka-bkhl-serif-normal.namingOverride]
  description = "Spatial efficient monospace font family for programming. Built from code. http://be5invis.github.io/Iosevka Custom build by Björn Lindström. https://git.sr.ht/~bkhl/dotfiles/tree/main/item/.src/iosevka"

  [buildPlans.iosevka-bkhl-serif-normal.variants]
  inherits = "buildPlans.iosevka-bkhl-sans-normal"

    [buildPlans.iosevka-bkhl-serif-normal.variants.design]
    capital-e = "serifed-capped"
    capital-f = "serifed-capped"
    capital-w = "rounded-vertical-sides-serifed"

    f = "serifed-crossbar-at-x-height"
    g = "double-storey"
    i = "serifed"
    l = "serifed"
    m = "short-leg-serifed"
    t = "bent-hook"
    w = "rounded-vertical-sides-serifed"
    y = "cursive-serifed"

    cyrl-capital-u = "cursive-serifed"

    long-s = "bent-hook-tailed-middle-serifed-xh"
    capital-eszet = "corner-serifed"
    eszet = "longs-s-lig-tailed-middle-serifed-xh"

    capital-lambda = "curly-base-serifed"

    one = "base-long-top-serif"

    guillemet = "curly"

    [buildPlans.iosevka-bkhl-serif-normal.variants.italic]
    g = "double-storey-open"

[buildPlans.iosevka-bkhl-serif-fixed]
family = "Iosevka BKHL Serif Fixed"
serifs = "slab"
spacing = "fixed"
noLigation = true
noCvSs = true

  [buildPlans.iosevka-bkhl-serif-fixed.namingOverride]
  description = "Spatial efficient monospace font family for programming. Built from code. http://be5invis.github.io/Iosevka Custom build by Björn Lindström. https://git.sr.ht/~bkhl/dotfiles/tree/main/item/.src/iosevka"

  [buildPlans.iosevka-bkhl-serif-fixed.variants]
  inherits = "buildPlans.iosevka-bkhl-serif-normal"
