- name: TLP repo enabled
  apt_repository:
    repo: 'ppa:linrunner/tlp'
    filename: tlp

- name: Update APT cache
  apt:
    update_cache: yes
  changed_when: false

- name: TLP packages installed
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - tlp
    - tlp-rdw
    - tp-smapi-dkms
    - acpi-call-dkms
    - intel-microcode

- name: TLP service started
  service:
    name: tlp
    state: started

- name: Disable Bluetooth on startup
  lineinfile:
    path: /etc/default/tlp
    regexp: '^DEVICES_TO_DISABLE_ON_STARTUP='
    line: 'DEVICES_TO_DISABLE_ON_STARTUP="bluetooth wwan"'
    insertafter: '^#DEVICES_TO_DISABLE_ON_STARTUP='

- name: Enable Wi-Fi on startup
  lineinfile:
    path: /etc/default/tlp
    regexp: '^DEVICES_TO_ENABLE_ON_STARTUP='
    line: 'DEVICES_TO_ENABLE_ON_STARTUP="wifi"'
    insertafter: '^#DEVICES_TO_ENABLE_ON_STARTUP='
