---
- name: st repository up to date
  git:
    repo: 'git://git.suckless.org/st'
    dest: '{{ st_source_path }}'
    force: true

- name: st repository clean
  command: git clean -f
  args:
    chdir: '{{ st_source_path }}'

- name: Patch fetched
  get_url:
    url: https://st.suckless.org/patches/boxdraw/st-boxdraw-2018-11-01-30ec9a3.patch
    dest: /tmp/st-boxdraw-2018-11-01-30ec9a3.patch
    checksum: sha256:8d9082636898151554df8d4fb3be077dca147ac172aa016e6509b3a78bd126c8

- name: Patch applied
  command: git apply /tmp/st-boxdraw-2018-11-01-30ec9a3.patch
  args:
    chdir: '{{ st_source_path }}'

- name: config.h in repository
  copy:
    src: config.h
    dest: '{{ st_source_path }}/config.h'

- name: st compiled
  make:
    chdir: '{{ st_source_path }}'
    target: all

- name: st copied to destination
  copy:
    src: '{{ st_source_path }}/st'
    dest: '{{ ansible_env.HOME }}/bin/st'
    mode: u=rwx,g=rx,o=rx
