---

- name: Add repository key
  register: result
  retries: 10
  until: not result.failed
  apt_key:
    id: CE3F3DE92099F7A4
    keyserver: keyserver.ubuntu.com
    state: present

- name: Add repository
  register: result
  retries: 10
  until: not result.failed
  apt_repository:
    repo: deb https://vagrant-deb.linestarve.com/ any main
    filename: vagrant

- name: Add filename to managed config files list
  set_fact:
    base_apt_config_files: >
      {{ base_apt_config_files + ['vagrant'] }}

- name: Install
  register: result
  retries: 10
  until: not result.failed
  apt:
    update_cache: true
    state: latest
    name: vagrant
