---
- name: st repository up to date
  git:
    repo: 'git://git.suckless.org/st'
    dest: '{{ st_source_path }}'
    force: true

- name: st repository clean
  command: git clean -f
  args:
    chdir: '{{ st_source_path }}'

- name: Patch fetched
  copy:
    src: boxdraw.patch
    dest: /tmp/boxdraw.patch

- name: Patch applied
  command: git apply /tmp/boxdraw.patch
  args:
    chdir: '{{ st_source_path }}'

- name: config.h in repository
  copy:
    src: config.h
    dest: '{{ st_source_path }}/config.h'

- name: st compiled
  make:
    chdir: '{{ st_source_path }}'
    target: all

- name: st copied to destination
  copy:
    src: '{{ st_source_path }}/st'
    dest: '{{ ansible_env.HOME }}/.local/bin/st'
    mode: u=rwx,g=rx,o=rx
