FROM docker.io/library/alpine:latest

RUN apk add bash curl python3 && \
    python -m venv /opt/opentype-feature-freezer && \
    /opt/opentype-feature-freezer/bin/pip install opentype-feature-freezer
