- name: TLP repo enabled
  apt_repository:
    repo: 'ppa:linrunner/tlp'
    filename: tlp

- name: Update APT cache
  apt:
    update_cache: yes
  changed_when: false

- name: Unused packages removed
  apt:
    state: absent
    name:
      - gedit
      - nano

- name: TLP packages installed
  apt:
    state: latest
    name:
      - tlp
      - tlp-rdw
      - tp-smapi-dkms
      - acpi-call-dkms
      - intel-microcode

- name: TLP service started
  service:
    name: tlp
    state: started

- name: Disable WWAN on startup
  lineinfile:
    path: /etc/default/tlp
    regexp: '^DEVICES_TO_DISABLE_ON_STARTUP='
    line: 'DEVICES_TO_DISABLE_ON_STARTUP="wwan"'
    insertafter: '^#DEVICES_TO_DISABLE_ON_STARTUP='

- name: Enable Bluetooth and Wi-Fi on startup
  lineinfile:
    path: /etc/default/tlp
    regexp: '^DEVICES_TO_ENABLE_ON_STARTUP='
    line: 'DEVICES_TO_ENABLE_ON_STARTUP="bluetooth wifi"'
    insertafter: '^#DEVICES_TO_ENABLE_ON_STARTUP='

- name: Configure modprobe for ThinkPad
  register: modprobe_config
  copy:
    src: thinkpad.conf
    dest: /etc/modprobe.d/thinkpad.conf

- name: Regenerate initramfs image
  command: update-initramfs -u
  when: modprobe_config.changed
