---

- name: Create temporary APT sources file
  tempfile:
    state: file
    suffix: .list
  changed_when: false
  register: base_temp_apt_file

- name: Set temporary file permission
  file:
    path: "{{ base_temp_apt_file.path }}"
    mode: 0644
  changed_when: false

- name: Add repositories to temporary sources file
  lineinfile:
    line: "{{ item }}"
    path: "{{ base_temp_apt_file.path }}"
  changed_when: false
  with_items:
    - >-
      deb mirror://mirrors.ubuntu.com/mirrors.txt
      {{ ansible_distribution_release }}
      main restricted
    - >-
      deb mirror://mirrors.ubuntu.com/mirrors.txt
      {{ ansible_distribution_release }}-updates
      main restricted
    - >-
      deb mirror://mirrors.ubuntu.com/mirrors.txt
      {{ ansible_distribution_release }}
      universe
    - >-
      deb mirror://mirrors.ubuntu.com/mirrors.txt
      {{ ansible_distribution_release }}-updates
      universe
    - >-
      deb mirror://mirrors.ubuntu.com/mirrors.txt
      {{ ansible_distribution_release }}
      multiverse
    - >-
      deb mirror://mirrors.ubuntu.com/mirrors.txt
      {{ ansible_distribution_release }}-updates
      multiverse
    - >-
      deb mirror://mirrors.ubuntu.com/mirrors.txt
      {{ ansible_distribution_release }}-backports
      main restricted universe multiverse
    - >-
      deb http://security.ubuntu.com/ubuntu
      {{ ansible_distribution_release }}-security
      main restricted
    - >-
      deb http://security.ubuntu.com/ubuntu
      {{ ansible_distribution_release }}-security
      universe
    - >-
      deb http://security.ubuntu.com/ubuntu
      {{ ansible_distribution_release }}-security
      multiverse
    - >-
      deb http://archive.canonical.com/ubuntu
      {{ ansible_distribution_release }}
      partner

- name: Update APT sources file
  copy:
    src: "{{ base_temp_apt_file.path }}"
    dest: /etc/apt/sources.list
    mode: 0644

- name: Packages removed
  apt:
    state: absent
    name:
      - nano

- name: Update APT cache and perform safe upgrade
  register: result
  retries: 10
  until: not result.failed
  apt:
    update_cache: true
    upgrade: safe
  changed_when: false

- name: Packages added
  register: result
  retries: 10
  until: not result.failed
  apt:
    update_cache: true
    state: latest
    name:
      # Applications
      - anki
      - audacity
      - chromium-browser
      - firefox
      - gthumb
      - libreoffice
      - mdp
      - mpv
      - simplescreenrecorder
      - usb-creator-gtk

      # Handy GUI tools
      - gparted
      - gnome-clocks
      - gnome-terminal
      - xclip

      # Appearance
      - fonts-dejavu
      - fonts-noto-color-emoji
      - fonts-tlwg-loma

      # Languages
      - firefox-locale-en
      - firefox-locale-sv
      - firefox-locale-th
      - language-pack-gnome-en
      - language-pack-gnome-sv
      - language-pack-gnome-th
      - wamerican
      - wbritish
      - wswedish

      # Handy terminal tools
      - bash-completion
      - curl
      - dos2unix
      - flac
      - httpie
      - jq
      - libimage-exiftool-perl
      - mmv
      - moreutils
      - mosh
      - rar
      - shntool
      - unrar
      - unzip
      - vorbis-tools
      - wkhtmltopdf
      - woof
      - xmlstarlet
      - zip
      - zsync

      # Development tools
      - bats
      - build-essential
      - bzr
      - cmake
      - debhelper
      - devscripts
      - dh-make
      - git
      - graphviz
      - libperl-critic-perl
      - mercurial
      - pkg-config
      - sqlite3
      - subversion
      - tidy

      # tmux build dependencies
      - pkg-config
      - libevent-dev

      # Python 3 build dependencies
      - zlib1g-dev
      - libffi-dev
      - libbz2-dev

      # Dependency for home/roles/desktop
      - python-psutil

      # Network tools
      - autossh
      - net-tools
      - network-manager-fortisslvpn-gnome
      - network-manager-l2tp-gnome
      - network-manager-openconnect-gnome
      - network-manager-openvpn-gnome
      - network-manager-pptp-gnome
      - network-manager-ssh-gnome
      - network-manager-vpnc-gnome
      - nfs-common
      - nmap
      - socat
      - sshpass
      - traceroute
      - whois

      # Printing
      - python3-smbc
      - smbclient

      # System tools
      - chrony
      - duply
      - krb5-user
      - ubuntu-restricted-addons

      # Ansible dependency
      - libssl1.0-dev

      # Perl
      - perl
      - libtest2-suite-perl

      # Useful for scripts that need secrets
      - libsecret-tools

      # Preferred tool by Ansible, for APT upgrades
      - aptitude

      # To mount Sony RX100 VI
      - exfat-fuse

- name: Use Firefox as default browser
  alternatives:
    name: x-www-browser
    path: /usr/bin/firefox

- name: Fix Bash completion for tar
  patch:
    src: bash-completion-tar.diff
    basedir: /usr/share/bash-completion/completions

- name: Global keyboard defaults set
  lineinfile:
    path: /etc/default/keyboard
    regexp: "^{{ item.key }}="
    line: '{{ item.key }}="{{ item.value }}"'
  with_items:
    - { key: "XKBLAYOUT", value: "us" }
    - { key: "XKBVARIANT", value: "altgr-intl" }
    - { key: "XKBOPTIONS", value: "compose:caps" }
    - { key: "BACKSPACE", value: "guess" }
