- name: Check for rustup
  stat: path={{ rustup_path }}
  register: rustup_stat

- name: Install rustup
  when: rustup_stat.stat.executable is not defined or not rustup_stat.stat.executable
  block:
    - name: Get rustup installation script
      get_url:
        url: https://static.rust-lang.org/rustup/rustup-init.sh
        checksum: sha256:0cb6ce30f81cfedeeac4c6b72d92859aa7652bdd3aa4759858a192129e8f6e1f
        dest: /tmp/rustup-init.sh

    - name: Run rustup installation
      command: sh /tmp/rustup-init.sh --no-modify-path -y

- name: Update rustup
  when: rustup_stat.stat.executable is defined and rustup_stat.stat.executable
  command: '{{ rustup_path }} update'

- name: Toolchains installed
  command: '{{ rustup_path }} toolchain install {{ item }}'
  with_items:
    - stable
    - beta
    - nightly

- name: stable components installed
  command: '{{ rustup_path }} component add {{ item }} --toolchain=stable'
  with_items:
    - clippy-preview
    - rustfmt-preview

- name: nightly components installed
  command: '{{ rustup_path }} component add {{ item }} --toolchain=nightly'
  with_items:
    - rls-preview
    - rust-analysis
    - rust-src

- name: Install programs from crates.io
  command: '{{ cargo_path }} install --force {{ item }}'
  with_items:
    - cargo-deb
    - shellharden
