- name: Check for rustup
  stat: path={{ rust_rustup_path }}
  register: rustup_stat

- name: Install rustup
  when: rustup_stat.stat.executable is not defined or not rustup_stat.stat.executable
  block:
    - name: Get rustup installation script
      get_url:
        url: https://static.rust-lang.org/rustup/rustup-init.sh
        checksum: sha256:40328ad8fa5cfc15cdb0446bb812a4bba4c22b5aee195cfb8d64b8ef1de5879c
        dest: /tmp/rustup-init.sh

    - name: Run rustup installation
      command: sh /tmp/rustup-init.sh --no-modify-path -y

- name: Update rustup
  when: rustup_stat.stat.executable is defined and rustup_stat.stat.executable
  command: '{{ rust_rustup_path }} update'

- name: Toolchains installed
  command: '{{ rust_rustup_path }} toolchain install {{ item }}'
  with_items:
    - stable
    - beta
    - nightly

- name: stable components installed
  command: '{{ rust_rustup_path }} component add {{ item }} --toolchain=stable'
  with_items:
    - clippy-preview
    - rustfmt-preview
    - rls-preview
    - rust-analysis
    - rust-src

- name: Install programs from crates.io
  command: '{{ rust_cargo_path }} install {{ item }}'
  args:
    creates: '{{ rust_cargo_root }}/bin/{{ item }}'
  with_items:
    - cargo-deb
    - shellharden
