---
fonts_directory: '{{ ansible_env.HOME }}/.local/share/fonts'
fonts_families:
  - Athiti
  - Chonburi
  - Itim
  - Kanit
  - Maitree
  - Mitr
  - Pridi
  - Prompt
  - Share
  - Share Tech
  - Share Tech Mono
  - Sriracha
  - Taviraj
  - Trirong
