---
fonts_directory: '{{ ansible_env.HOME }}/.local/share/fonts'
fonts_families:
  - Athiti
  - Chonburi
  - Itim
  - Kanit
  - Maitree
  - Mitr
  - Pridi
  - Prompt
  - Share
  - Share Tech
  - Share Tech Mono
  - Sriracha
  - Taviraj
  - Trirong

ui_usertheme_basename: 'user-theme@gnome-shell-extensions.gcampax.github.com'
ui_usertheme_filename: '{{ ui_usertheme_basename }}.v34.shell-extension.zip'
ui_usertheme_url: 'https://extensions.gnome.org/extension-data/{{ ui_usertheme_filename }}'
ui_usertheme_checksum: 'sha256:cc1e7f160d67535f0b551fef80c81abcd4c031c907bdda6ca1937bb3ee321eff'
ui_usertheme_path: '{{ ansible_env.HOME }}/.local/share/gnome-shell/extensions/{{ ui_usertheme_basename }}'
