---

- name: Packages added
  register: result
  retries: 10
  until: not result.failed
  apt:
    update_cache: true
    state: latest
    name:
      - calibre
      - hexchat
      - remmina
      - swi-prolog
