#!/bin/sh

# To be put in /etc/NetworkManager/dispatcher.d/

myname=${0##*/}
log() { logger -p user.info -t "${myname}[$$]" "$*"; }
IFACE=$1
ACTION=$2

case ${IFACE} in
    eth*|usb*|en*)
        case ${ACTION} in
            up)
                log "disabling wifi radio"
                nmcli radio wifi off
                ;;
            # down)
            #     log "enabling wifi radio"
            #     nmcli "${nmobj}" wifi on
            #     ;;
        esac
        ;;
esac
