- name: Check for Exercism CLI client
  stat:
    path: '{{ ansible_env.HOME }}/.local/bin/exercism'
  register: exercism_check

- when: exercism_check.stat.executable is not defined or not exercism_check.stat.executable
  block:
    - name: Download Exercism
      get_url:
        url: https://github.com/exercism/cli/releases/download/v3.0.5/exercism-linux-64bit.tgz
        dest: /tmp/exercism-linux-64bit.tgz
        checksum: sha256:d32a63542ca3588faeaa02f6f2a28c50a6eec50354d2838cd82470d262dff020

    - name: Unpack exercism
      unarchive:
        src: /tmp/exercism-linux-64bit.tgz
        dest: '{{ ansible_env.HOME }}/.local/bin/'
        exclude: 'shell'

    - name: Exercism CLI client is executable file
      file:
        path: '{{ ansible_env.HOME }}/.local/bin/exercism'
        state: file
        mode: 0755

- name: Check exercism configuration
  command: exercism configure
  register: exercism_config
  changed_when: false

- name: Exercism directory set
  command: exercism configure --workspace={{ ansible_env.HOME }}/Development/exercism
  when: exercism_config.stdout is not match('^Workspace:.*' + ansible_env.HOME + '/Development/exercism')
