- name: Check if GitHub is reachable
  wait_for: host=github.com port=443 timeout=1
  register: github_reachable
  ignore_errors: yes

- name: Start proxy/tunnel
  when: github_reachable.failed
  block:
    - name: Start Tinyproxy
      local_action: command tinyproxy -c tinyproxy.conf -d
      async: 86400
      poll: 0

    - name: Start SSH tunnel for HTTP proxy
      local_action: command ssh -M -S ssh.socket -fnNT -p {{ ansible_port }} -L 8888:localhost:8888 {{ ansible_user }}@{{ ansible_host }}
