---
base_repos:
  - name: Google Chrome
    apt_key:
      url: https://dl-ssl.google.com/linux/linux_signing_key.pub
      id: 9534C9C4130B4DC9927992BF4F30B6B4C07CB649
    apt_repository:
      repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
      filename: google-chrome

  - name: Skype
    apt_key:
      url: https://repo.skype.com/data/SKYPE-GPG-KEY
      id: F60A017E3CA5558FAF2439556B4A0000A4EBB320
    apt_repository:
      repo: deb [arch=amd64] https://repo.skype.com/deb stable main
      filename: skype-stable

  - name: TelRed
    apt_key:
      id: 9454C19A66B920C83DDF696E07C8CCAFCE49F8C5
    apt_repository:
      repo: 'deb https://tel.red/repos/ubuntu {{ ansible_distribution_release }} non-free'
      filename: telred

  - name: Signal
    apt_key:
      url: https://updates.signal.org/desktop/apt/keys.asc
      id: D980A17457F6FB06
    apt_repository:
      repo: deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
      filename: signal

  - name: Pick
    apt_key:
      id: 0EDF8453E8783FF786AF6DED2D2F9F912F2229FF
    apt_repository:
      repo: deb http://ppa.launchpad.net/sil/pick/ubuntu xenial main
      filename: pick

  - name: Teamviewer stable
    apt_key:
      id: C5E224500C1289C0
    apt_repository:
      repo: deb http://linux.teamviewer.com/deb stable main
      filename: teamviewer
  - name: Teamviewer preview
    apt_key:
      id: C5E224500C1289C0
    apt_repository:
      repo: deb http://linux.teamviewer.com/deb preview main
      filename: teamviewer

  - name: docker-gc
    apt_repository:
      repo: ppa:nschloe/docker-gc-nightly
      filename: docker-gc

  - name: Picard
    apt_repository:
      repo: ppa:musicbrainz-developers/stable
      filename: musicbrainz

  - name: SWI Prolog
    apt_key:
      id: EF8406856DBFCA18
    apt_repository:
      repo: 'deb http://ppa.launchpad.net/swi-prolog/devel/ubuntu {{ ansible_distribution_release }} main'
      filename: swi-prolog

  - name: Vagrant
    apt_key:
      id: CE3F3DE92099F7A4
    apt_repository:
      repo: deb https://vagrant-deb.linestarve.com/ any main
      filename: vagrant

  - name: Wesnoth
    apt_repository:
      repo: ppa:vincent-c/wesnoth
      filename: wesnoth

  - name: Vim
    apt_repository:
      repo: ppa:jonathonf/vim
      filename: vim

  - name: Virtualbox
    apt_key:
      id: A2F683C52980AECF
      url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    apt_repository:
      repo: 'deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib'
      filename: virtualbox

  - name: Nextcloud
    apt_repository:
      repo: ppa:nextcloud-devs/client
      filename: nextcloud

  - name: Sayonara
    apt_repository:
      repo: ppa:lucioc/sayonara
      filename: sayonara

  - name: Zeal
    apt_repository:
      repo: ppa:zeal-developers/ppa
      filename: zeal

base_packages_install:
  # Applications
  - anki
  - audacity
  - calibre
  - google-chrome-stable
  - gthumb
  - hexchat
  - libreoffice
  - mdp
  - nextcloud-client
  - picard
  - remmina
  - sayonara
  - signal-desktop
  - simplescreenrecorder
  - sky
  - skypeforlinux
  - teamviewer
  - thonny
  - usb-creator-gtk
  - vim-gtk3
  - virtualbox-6.0
  - zeal

  # Handy GUI tools
  - gnome-clocks
  - pick-colour-picker
  - xclip

  # Games
  - wesnoth

  # Appearance
  - fonts-noto
  - fonts-noto-color-emoji
  - gnome-tweak-tool

  # My languages
  - firefox-locale-en
  - firefox-locale-sv
  - firefox-locale-th
  - language-pack-gnome-en
  - language-pack-gnome-sv
  - language-pack-gnome-th
  - wamerican
  - wbritish
  - wswedish

  # Handy terminal tools
  - curl
  - flac
  - httpie
  - jq
  - libimage-exiftool-perl
  - mmv
  - moreutils
  - mosh
  - pandoc
  - rar
  - shntool
  - unrar
  - unzip
  - vorbis-tools
  - wkhtmltopdf
  - woof
  - xmlstarlet
  - zip
  - zsync

  # Development tools
  - bats
  - build-essential
  - bzr
  - cmake
  - debhelper
  - devscripts
  - dh-make
  - docker-compose
  - docker-gc
  - docker.io
  - git
  - graphviz
  - libperl-critic-perl
  - python-minimal
  - python-pip
  - python3-minimal
  - python3-pip
  - shellcheck
  - swi-prolog
  - sqlite3
  - subversion
  - tidy
  - vagrant

  # Network tools
  - autossh
  - dnsmasq
  - net-tools
  - network-manager-openconnect-gnome
  - network-manager-openvpn-gnome
  - network-manager-vpnc-gnome
  - nmap
  - resolvconf
  - socat
  - traceroute
  - whois

  # Printing
  - python3-smbc
  - smbclient

  # System tools
  - chrony
  - duply
  - krb5-user
  - ubuntu-restricted-addons

  # Ansible dependency
  - libssl1.0-dev

  # Erlang dependencies
  - autoconf
  - libncurses5-dev

  # st dependencies
  - libx11-dev
  - libxft-dev

  # Useful for scripts that need secrets
  - libsecret-tools

  # Preferred tool by Ansible, for APT upgrades
  - aptitude

base_packages_uninstall:
  - evolution
  - nano
