---

godot_version: "3.1.1"
godot_filename: "Godot_v{{ godot_version }}-stable_x11.64"
godot_archive_filename: "{{ godot_filename }}.zip"
godot_download_url: "https://downloads.tuxfamily.org/godotengine/\
                     {{ godot_version }}/{{ godot_archive_filename }}"
godot_archive_checksum: >
  sha256:42be2707ef59ef751fba722823cb6decb52dc6c33c994939026b3e0da44f24b0
godot_bin_path: "{{ user_bin_directory}}/godot"
