- name: Add Vim PPA
  apt_repository:
    repo: ppa:jonathonf/vim
    filename: vim

- name: Add filename to managed config files list
  set_fact:
    base_apt_config_files: "{{ base_apt_config_files + ['vim'] }}"

- name: Install Vim
  register: result
  retries: 10
  until: not result.failed
  apt:
    update_cache: true
    state: latest
    name: vim-gtk3

- name: Set Vim as default editor
  alternatives:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
  with_items:
    - { name: editor, path: /usr/bin/vim.gtk3 }
    - { name: ex, path: /usr/bin/vim.gtk3 }
    - { name: rview, path: /usr/bin/vim.gtk3 }
    - { name: rvim, path: /usr/bin/vim.gtk3 }
    - { name: vi, path: /usr/bin/vim.gtk3 }
    - { name: view, path: /usr/bin/vim.gtk3 }
    - { name: vim, path: /usr/bin/vim.gtk3 }
    - { name: vimdiff, path: /usr/bin/vim.gtk3 }
