- name: Window title font set
  dconf:
    key: /org/gnome/desktop/wm/preferences/titlebar-font
    value: "'Noto Sans Bold 11'"

- name: Interface font set
  dconf:
    key: /org/gnome/desktop/interface/font-name
    value: "'Noto Sans 11'"

- name: Document font set
  dconf:
    key: /org/gnome/desktop/interface/document-font-name
    value: "'Noto Sans 11'"

- name: Monospace font set
  dconf:
    key: /org/gnome/desktop/interface/monospace-font-name
    value: "'Noto Sans Mono 11'"

- name: Clipboard GNOME Shell extension checked out
  git:
    repo: https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator.git
    dest: '{{ ansible_env.HOME }}/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com'

- name: Clipboard GNOME Shell extension enabled
  command: gnome-shell-extension-tool --enable-extension=clipboard-indicator@tudmotu.com
  register: clipboard_enabled_result
  changed_when: >
    clipboard_enabled_result.stderr != "'clipboard-indicator@tudmotu.com' is already enabled."
  failed_when: >
    clipboard_enabled_result.rc != 0
    and clipboard_enabled_result.stderr != "'clipboard-indicator@tudmotu.com' is already enabled."

- name: Clipboard GNOME Shell extension reloaded
  command: gnome-shell-extension-tool --reload-extension=clipboard-indicator@tudmotu.com
  when: >
    clipboard_enabled_result.stderr != "'clipboard-indicator@tudmotu.com' is already enabled."

- name: Show dock at bottom of screen
  dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/dock-position
    value: "'BOTTOM'"

- name: Auto-hide dock
  dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/dock-fixed
    value: 'false'

- name: Display date in top bar
  dconf:
    key: /org/gnome/desktop/interface/clock-show-date
    value: 'true'

- name: Enable world clocks
  dconf:
    key: /org/gnome/clocks/world-clocks
    value: >
      [{'location': <(uint32 2, <('Los Angeles', 'KCQT', true,
         [(0.59370283970450188, -2.0644336110828618)],
         [(0.59432360095955872, -2.063741622941031)])>)>},
       {'location': <(uint32 2, <('New York', 'KNYC', true,
         [(0.71180344078725644, -1.2909618758762367)],
         [(0.71059804659265924, -1.2916478949920254)])>)>},
       {'location': <(uint32 2, <('London', 'EGLL', true,
         [(0.89855367075064974, -0.0078539816339744835)],
         [(0.89884456477707964, -0.0020362232784242244)])>)>},
       {'location': <(uint32 2, <('Stockholm', 'ESSB', true,
         [(1.0358529110586345, 0.31328660073298215)],
         [(1.0355620170322046, 0.31503192998497648)])>)>},
       {'location': <(uint32 2, <('Johannesburg', 'FAOR', true,
         [(-0.4561127053700873, 0.49276461966196816)],
         [(-0.45727626402251431, 0.49014662578397672)])>)>},
       {'location': <(uint32 2, <('Mumbai', 'VABB', true,
         [(0.33364878115734681, 1.271472360077869)],
         [(0.33117622556592408, 1.2710505663575395)])>)>},
       {'location': <(uint32 2, <('Bangkok', 'VTBD', true,
         [(0.24289166005364171, 1.7558012275062955)],
         [(0.23998277214922031, 1.754346792280731)])>)>},
       {'location': <(uint32 2, <('Sydney', 'YSSY', true,
         [(-0.59253928105207498, 2.6386469349889961)],
          [(-0.59137572239964786, 2.6392287230418559)])>)>}]
