- name: Check for rustup
  stat: path={{ rustup_path }}
  register: rustup_stat

- name: Run in Cargo environment
  environment:
    CARGO_HOME: "{{ cargo_root }}"
  block:
    - name: Install rustup
      when: >
        rustup_stat.stat.executable is not defined
        or not rustup_stat.stat.executable
      block:
        - name: Get rustup installation script
          get_url:
            url: https://static.rust-lang.org/rustup/rustup-init.sh
            dest: /tmp/rustup-init.sh
          changed_when: false

        - name: Run rustup installation
          command: sh /tmp/rustup-init.sh --no-modify-path -y

    - name: Update rustup
      when: rustup_stat.stat.executable is defined and rustup_stat.stat.executable
      command: "{{ rustup_path }} update"

    - name: Check rustup profile
      command: "{{ rustup_path }} set profile"
      changed_when: false
      register: rustup_profile

    - name: Set rustup profile to default
      command: "{{ rustup_path }} set profile default"
      when: >
        "profile set to 'default'" not in rustup_profile.stderr

    - name: Stable toolchain installed
      command: "{{ rustup_path }} toolchain install stable"

    - name: stable components installed
      command: "{{ rustup_path }} component add {{ item }} --toolchain=stable"
      with_items:
        - clippy
        - rustfmt
        - rls
        - rust-analysis
        - rust-src
