- name: Create temporary font download directory
  tempfile:
    state: directory
    suffix: fonts
  register: temp_font_directory

- name: Download fonts
  get_url:
    url: 'https://fonts.google.com/download?family={{ item | urlencode }}'
    dest: '{{ temp_font_directory.path }}/{{ item }}.zip'
  with_items: '{{ fonts_families }}'

- name: Create font directories
  file:
    path: "{{ fonts_directory }}/{{ item }}"
    state: directory
  with_items: '{{ fonts_families }}'

- name: Unpack fonts
  unarchive:
    src: '{{ temp_font_directory.path }}/{{ item }}.zip'
    dest: '{{ fonts_directory }}/{{ item }}'
  with_items: '{{ fonts_families }}'
