- name: Python psutils installed
  pip:
    executable: pip2
    extra_args: --user
    name: psutil
    state: present

# FIXME: Make a nested loop to automatically generate numbers and create this list.
- name: One custom keyboard shortcut enabled
  dconf:
    key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings'
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"

- name: Keyboard shortcut for Tilix Quake mode set
  dconf:
    key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/{{ item.action }}'
    value: "'{{ item.key }}'"
  with_items:
    - { action: 'name', key: 'Tilix Quake Mode' }
    - { action: 'command', key: 'tilix --quake' }
    - { action: 'binding', key: '<Super>Return' }

- name: Window manager keyboard shortcuts set
  dconf:
    key: '/org/gnome/desktop/wm/keybindings/{{ item.action }}'
    value: "['{{ item.key }}']"
  with_items:
    - { action: 'switch-applications', key: '<Super>Tab' }
    - { action: 'switch-applications-backward', key: '<Shift><Super>Tab' }
    - { action: 'switch-group', key: '<Super>grave' }
    - { action: 'switch-group-backward', key: '<Shift><Super>grave' }
    - { action: 'toggle-fullscreen', key: '<Super>f' }
