---
- name: digiKam downloaded
  get_url:
    url: >
      https://download.kde.org/stable/digikam/6.3.0/digikam-6.3.0-x86-64.appimage
    dest: "{{ user_bin_directory }}/digikam"
    mode: 0755
    checksum: >
      sha256:6ad9df76be77e28237d4cdffd8dff92f06d0e2852e41404f06798e8f6dc9973d
