- name: Clone repository
  git:
    repo: https://github.com/tmux/tmux.git
    dest: '{{ tmux_src_directory }}'
    version: '{{ tmux_version }}'

- name: Run autogen.sh
  command: './autogen.sh'
  args:
    chdir: '{{ tmux_src_directory }}'

- name: Run configure
  command: './configure --prefix={{ tmux_install_prefix }}'
  args:
    chdir: '{{ tmux_src_directory }}'

- name: Build and install
  make:
    chdir: '{{ tmux_src_directory }}'
    target: install
