---

- name: Check Godot version
  command: "{{ godot_bin_path }} --version"
  register: check_result
  changed_when: false
  failed_when: false

- when: >
    check_result.rc != 255
    or check_result.stdout != godot_version + '.stable.official'
  block:
    - name: Download archive
      get_url:
        url: "{{ godot_download_url }}"
        dest: "/tmp/{{ godot_archive_filename }}"
        checksum: "{{ godot_archive_checksum }}"

    - name: Unpack archive
      unarchive:
        src: "/tmp/{{ godot_archive_filename }}"
        dest: /tmp
        remote_src: true
        extra_opts:

    - name: Put executable in place
      copy:
        src: "/tmp/{{ godot_filename }}"
        dest: "{{ godot_bin_path }}"
        mode: u+rwx,g+rx,o+rx
