---
- name: Packages installed
  apt:
      state: latest
      name:
          - tp-smapi-dkms
          - acpi-call-dkms
          - intel-microcode

- name: TLP service restarted
  service:
      name: tlp
      state: restarted

- name: Configure modprobe for ThinkPad
  register: modprobe_config
  copy:
      src: thinkpad_x250.conf
      dest: /etc/modprobe.d/thinkpad_x250.conf

- name: Regenerate initramfs image
  command: update-initramfs -u
  when: modprobe_config.changed
