- name: Get Python environment directory
  set_fact:
    python_directory: '{{ ansible_env.HOME }}/opt/python'

- name: Get Ansible path
  command: which ansible
  changed_when: false
  register: ansible_path_which_result

- name: Store Ansible path
  set_fact:
    ansible_path: '{{ ansible_path_which_result.stdout | trim }}'

- name: Check for libssl-dev
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  command: dpkg-query --show --showformat='${db:Status-Status}\n' libssl-dev
  changed_when: false
  ignore_errors: yes
  register: libssl_dev_check

- name: Store whether libssl-dev is installed
  set_fact:
    libssl_dev_present: "{{ (libssl_dev_check.stdout | trim) == 'installed' }}"

- name: Create Python environment directory
  file: name='{{ python_directory }}' state=directory

- name: Clear out Python environment directory
  when: not ansible_path.startswith(python_directory)
  file:
    state: '{{ item }}'
    path: '{{ python_directory }}'
  with_items:
    - absent
    - directory

- name: Install Python 3 packages
  pip:
    executable: pip3
    extra_args: --user
    name:
      - black
      - csvkit
      - isort
      - pre-commit
      - python-language-server
    state: latest

- name: Install Ansible
  when: libssl_dev_present
  pip:
    executable: pip3
    extra_args: --user
    name: ansible
    state: latest

- name: Check for Poetry
  stat:
    path: '{{ poetry_path }}'
  register: poetry_check

- when: poetry_check.stat.executable is not defined or not poetry_check.stat.executable
  block:
    - name: Poetry installer downloaded
      get_url:
        url: https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
        dest: /tmp/get-poetry.py
        checksum: sha256:f03921551eef01651c6f0dc88c9c84c3d4b5c1e9835affbf87aebacf7b0386f1

    - name: Poetry installed
      command: python3 /tmp/get-poetry.py --yes

- name: Poetry updated
  when: poetry_check.stat.executable is defined and poetry_check.stat.executable
  command: poetry self:update
