variables:
  CI_REGISTRY_IMAGE_BASE: base
  CI_DOCKER_FILE_BASE: .local/share/playbooks/Dockerfile.base

  CI_REGISTRY_IMAGE_SYSTEM: system
  CI_DOCKER_FILE_SYSTEM: .local/share/playbooks/Dockerfile.system

  CI_REGISTRY_IMAGE_HOME: home
  CI_DOCKER_FILE_HOME: .local/share/playbooks/Dockerfile.home

stages:
  - base
  - system
  - home

base:
  stage: base
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - >-
      docker
      pull $CI_REGISTRY/$CI_PROJECT_PATH/$CI_REGISTRY_IMAGE_BASE:master
      || true
    - >-
      docker
      pull $CI_REGISTRY/$CI_PROJECT_PATH/$CI_REGISTRY_IMAGE_BASE:$CI_COMMIT_REF_NAME
      || true
    - >-
      docker build
      --file $CI_DOCKER_FILE_BASE
      --cache-from $CI_REGISTRY_IMAGE_BASE:$CI_COMMIT_REF_NAME
      --tag $CI_REGISTRY/$CI_PROJECT_PATH/$CI_REGISTRY_IMAGE_BASE:$CI_COMMIT_SHA
      --tag $CI_REGISTRY/$CI_PROJECT_PATH/$CI_REGISTRY_IMAGE_BASE:$CI_COMMIT_REF_NAME .
    - >-
      docker
      push $CI_REGISTRY/$CI_PROJECT_PATH/$CI_REGISTRY_IMAGE_BASE:$CI_COMMIT_SHA
    - >-
      docker
      push $CI_REGISTRY/$CI_PROJECT_PATH/$CI_REGISTRY_IMAGE_BASE:$CI_COMMIT_REF_NAME
  only:
    changes:
      - .local/share/playbooks/gitlab-ci.yml
      - .local/share/playbooks/Dockerfile.base

system:
  stage: system
  dependencies:
    - base
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - >-
      docker
      pull $CI_REGISTRY/$CI_PROJECT_PATH/$CI_REGISTRY_IMAGE_SYSTEM:master
      || true
    - >-
      docker
      pull $CI_REGISTRY/$CI_PROJECT_PATH/$CI_REGISTRY_IMAGE_SYSTEM:$CI_COMMIT_REF_NAME
      || true
    - >-
      docker build
      --build-arg
      image=$CI_REGISTRY/$CI_PROJECT_PATH/$CI_REGISTRY_IMAGE_BASE:$CI_COMMIT_REF_NAME
      --build-arg
      project_dir=$CI_PROJECT_DIR
      --file $CI_DOCKER_FILE_SYSTEM
      --cache-from $CI_REGISTRY_IMAGE_SYSTEM:$CI_COMMIT_REF_NAME
      --tag
      $CI_REGISTRY/$CI_PROJECT_PATH/$CI_REGISTRY_IMAGE_SYSTEM:$CI_COMMIT_SHA
      --tag $CI_REGISTRY/$CI_PROJECT_PATH/$CI_REGISTRY_IMAGE_SYSTEM:$CI_COMMIT_REF_NAME
      .
    - >-
      docker
      push $CI_REGISTRY/$CI_PROJECT_PATH/$CI_REGISTRY_IMAGE_SYSTEM:$CI_COMMIT_SHA
    - >-
      docker
      push $CI_REGISTRY/$CI_PROJECT_PATH/$CI_REGISTRY_IMAGE_SYSTEM:$CI_COMMIT_REF_NAME
  only:
    changes:
      - .local/share/playbooks/gitlab-ci.yml
      - .local/share/playbooks/Dockerfile.system
      - .local/share/playbooks/system/**/*

home:
  stage: home
  dependencies:
    - system
  image: $CI_REGISTRY/$CI_PROJECT_PATH/$CI_REGISTRY_IMAGE_SYSTEM:$CI_COMMIT_REF_NAME
  script:
    - |
      sudo --set-home --login --user test bash -e -x << EOF

      mkdir --verbose .config

      git clone --bare --verbose "${CI_PROJECT_DIR}" .config/dotfiles
      git --git-dir=.config/dotfiles --work-tree=. checkout --force

      cd .local/share/playbooks

      ansible-playbook --inventory=inventory --limit=test home/home.yml
      EOF
  only:
    changes:
      - .local/share/playbooks/gitlab-ci.yml
      - .local/share/playbooks/home/**/*
