Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/bionic64'

  config.vm.provider 'virtualbox'

  config.vm.provision 'vagrant', type:'ansible' do |ansible|
      ansible.playbook = 'vagrant.yml'
  end

  config.vm.provision 'system', type:'ansible' do |ansible|
      ansible.playbook = 'system/system.yml'
      ansible.verbose = true
  end

  config.vm.provision 'push', type:'ansible' do |ansible|
      ansible.playbook = 'push/push.yml'
      ansible.verbose = true
  end
end
