- name: Check for rustup
  stat: path={{ rustup_path }}
  register: rustup_stat

- name: Install rustup
  when: rustup_stat.stat.executable is not defined or not rustup_stat.stat.executable
  block:
    - name: Get rustup installation script
      get_url:
        url: https://static.rust-lang.org/rustup/rustup-init.sh
        checksum: sha256:22aa1f7f4c4b9be99a9d7e13ad45b2aec6714165a0578dd5ef81ca11f55ea24e
        dest: /tmp/rustup-init.sh

    - name: Run rustup installation
      command: sh /tmp/rustup-init.sh --no-modify-path -y

- name: Update rustup
  when: rustup_stat.stat.executable is defined and rustup_stat.stat.executable
  command: '{{ rustup_path }} update'

- name: Toolchains installed
  command: '{{ rustup_path }} toolchain install {{ item }}'
  with_items:
    - stable
    - beta
    - nightly

- name: Components installed
  command: '{{ rustup_path }} component add {{ item }}'
  with_items:
    - rustfmt-preview
