---

- name: Add Skype repository key
  register: result
  retries: 10
  until: not result.failed
  apt_key:
    url: https://repo.skype.com/data/SKYPE-GPG-KEY
    id: F60A017E3CA5558FAF2439556B4A0000A4EBB320
    state: present

- name: Add Skype repository
  register: result
  retries: 10
  until: not result.failed
  apt_repository:
    repo: deb [arch=amd64] https://repo.skype.com/deb stable main
    filename: skype

- name: Add filenames to managed config files list
  set_fact:
    base_apt_config_files: >
      {{ base_apt_config_files + ['skype'] }}

- name: Install Skype
  register: result
  retries: 10
  until: not result.failed
  apt:
    update_cache: true
    state: latest
    name: skypeforlinux
